version: "3.9"
services:
  dockerproxy:
    image: tecnativa/docker-socket-proxy
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    container_name: dockerproxy
    privileged: true
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 2375:2375
    environment:
      BUILD: 1
      COMMIT: 1
      CONFIGS: 1
      CONTAINERS: 1
      DISTRIBUTION: 1
      EXEC: 1
      IMAGES: 1
      INFO: 1
      NETWORKS: 1
      NODES: 1
      PLUGINS: 1
      SERVICES: 1
      SESSSION: 1
      SWARM: 1
      POST: 1

  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_VOLUMES}/duplicati/data:/config
      - ${DOCKER_LARGE_VOLUMES}/duplicati/backups:/backups
      - ${DOCKER_VOLUMES}:/source
    ports:
      - 8200:8200
    restart: unless-stopped

  tailscale:
    container_name: tailscale
    privileged: true
    network_mode: "host"
    image: tailscale/tailscale:stable
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
        - "${DOCKER_VOLUMES}/tailscale/data:/var/lib"
        - "/dev/net/tun:/dev/net/tun"
    cap_add:
        - net_admin
        - sys_module
    command: tailscaled
    restart: unless-stopped
    
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:s6
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    restart: unless-stopped
    volumes:
      - /:/srv
      - ${DOCKER_VOLUMES}/filebrowser/data:/config
      - ${DOCKER_VOLUMES}/filebrowser/data/database:/database
    ports:
      - 8080:80

  watchtower:
    environment:
      TZ: ${TZ}
    image: containrrr/watchtower
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 10444:8080