version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    network_mode: "host"
    restart: always
    image: ghcr.io/blakeblackshear/frigate:stable
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    shm_size: "120mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker-volumes/frigate/data:/config
      - type: volume
        source: frigate_media_volume
        target: /media/frigate
        volume:
          nocopy: true
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000

  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - DOCKER_TLS_VERIFY=0
    volumes:
      - /docker-volumes/homeassistant/data:/config
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    privileged: true
    network_mode: host

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - TZ=Asia/Riyadh
    restart: always
    volumes:
      - /docker-volumes/mqtt/config:/mosquitto/config
      - /docker-volumes/mqtt/data:/mosquitto/data
      - /docker-volumes/mqtt/log:/mosquitto/log
    network_mode: host

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: always
    image: koenkk/zigbee2mqtt
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    network_mode: host
    privileged: true
    volumes:
      - /docker-volumes/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - TZ=Asia/Riyadh

volumes:
  frigate_media_volume:
    driver_opts:
      type: cifs    
      device: //10.10.100.101/chalet
      o: "username=frigate,password=QJBo5fQK8DL2jsPkqe3BGuFC,vers=3.0,uid=1026,gid=101"