version: "3.9"
services:
  dockerproxy:
    image: tecnativa/docker-socket-proxy
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    container_name: dockerproxy
    privileged: true
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 2375:2375
    environment:
      - BUILD=1
      - COMMIT=1
      - CONFIGS=1
      - CONTAINERS=1
      - DISTRIBUTION=1
      - EXEC=1
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - NODES=1
      - PLUGINS=1
      - SERVICES=1
      - SESSSION=1
      - SWARM=1
      - POST=1

  tailscale:
    privileged: true
    hostname: chalet-docker
    network_mode: "host"
    container_name: tailscale
    image: tailscale/tailscale:latest
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
        - "/docker-large-volumes/tailscale/data:/var/lib"
        - "/dev/net/tun:/dev/net/tun"
    cap_add:
    - NET_ADMIN
    - NET_RAW
    command: tailscaled
    restart: always

  watchtower:     
    image: containrrr/watchtower
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    container_name: watchtower 
    restart: always 
    environment: 
      WATCHTOWER_SCHEDULE: "0 0 1 * * *" 
      TZ: Asia/Riyadh 
      WATCHTOWER_CLEANUP: "true" 
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock

  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:s6
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      TZ: 'Asia/Riyadh'
      PUID: 0
      PGID: 0
    restart: always
    volumes:
      - /docker-volumes:/srv
      - /docker-volumes/filebrowser/data:/config
      - /docker-volumes/filebrowser/data/database:/database
    ports:
      - 8080:80

  backup:
    container_name: backup
    image: offen/docker-volume-backup:v2
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      TZ: 'Asia/Riyadh'
      BACKUP_CRON_EXPRESSION: '0 2 * * *'
      BACKUP_FILENAME: 'chalet_docker_volumes_backup-%Y-%m-%dT%H-%M-%S.tar.gz'
      BACKUP_LATEST_SYMLINK: 'backup_latest.tar.gz'
      BACKUP_EXCLUDE_REGEXP: '.*log.*'
      WEBDAV_URL: 'https://cloud.visioninvestment.sa/remote.php/dav/files/mohammed/'
      WEBDAV_PATH: '/126 Backups/Smart Home Backups/Client 001/'
      WEBDAV_USERNAME: 'mohammed'
      WEBDAV_PASSWORD: 'dHqRA-MLctf-SP99w-38AYL-W4jGH'
      BACKUP_RETENTION_DAYS: '256'
      GZIP_PARALLELISM: 0
    restart: always
    volumes:
      - /docker-volumes:/backup:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
