version: '3.8'

services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PLEX_PUID}
      - PGID=${PLEX_PGID}
      - VERSION=docker
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${DOCKER_LARGE_VOLUMES}/plex/data:/config
      - ${MEDIA_VOLUMES}:${MEDIA_VOLUMES}
    restart: always

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    container_name: nzbget
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_VOLUMES}/nzbget/data:/config
      - ${MEDIA_VOLUMES}:${MEDIA_VOLUMES}
    ports:
      - 6789:6789
    restart: always

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    depends_on:
      - nzbget
    ports:
      - 8989:8989
    volumes:
      - ${DOCKER_VOLUMES}/sonarr/data:/config
      - ${MEDIA_VOLUMES}:${MEDIA_VOLUMES}
    environment:
      - TZ=${TZ}
  
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    depends_on:
      - nzbget
    ports:
      - 7878:7878
    volumes:
      - ${DOCKER_VOLUMES}/radarr/data:/config
      - ${MEDIA_VOLUMES}:${MEDIA_VOLUMES}
    environment:
      - TZ=${TZ}

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    environment:
        - LOG_LEVEL=info
        - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - ${DOCKER_LARGE_VOLUMES}/overseerr/data:/app/config

