version: '3.8'

services:
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    container_name: nzbget
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_VOLUMES}/nzbget/data:/config
      - media:${MEDIA_VOLUMES}
      - intermediate:/mnt/intermediate
      - /mnt/usb1:/mnt/usb1
    ports:
      - 6789:6789
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    depends_on:
      - nzbget
    ports:
      - 8989:8989
    volumes:
      - ${DOCKER_VOLUMES}/sonarr/data:/config
      - media:${MEDIA_VOLUMES}
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
  
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    depends_on:
      - nzbget
    ports:
      - 7878:7878
    volumes:
      - ${DOCKER_VOLUMES}/radarr/data:/config
      - media:${MEDIA_VOLUMES}
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 5055:5055
    volumes:
      - ${DOCKER_LARGE_VOLUMES}/overseerr/data:/app/config

volumes:
  media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER}
      device: :${MEDIA_VOLUMES}
  intermediate:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER}
      device: :/mnt/intermediate