version: "3.9"
services:
  dockerproxy:
    image: tecnativa/docker-socket-proxy
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    container_name: dockerproxy
    privileged: true
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 2375:2375
    environment:
      BUILD: 1
      COMMIT: 1
      CONFIGS: 1
      CONTAINERS: 1
      DISTRIBUTION: 1
      EXEC: 1
      IMAGES: 1
      INFO: 1
      NETWORKS: 1
      NODES: 1
      PLUGINS: 1
      SERVICES: 1
      SESSSION: 1
      SWARM: 1
      POST: 1

  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_VOLUMES}/duplicati/data:/config
      - ${MEDIA_VOLUMES}/backups:/backups
      - ${DOCKER_VOLUMES}:/source
    ports:
      - 8200:8200
    restart: unless-stopped
    
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:s6
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    restart: unless-stopped
    volumes:
      - /:/srv
      - ${DOCKER_VOLUMES}/filebrowser/data:/config
      - ${DOCKER_VOLUMES}/filebrowser/data/database:/database
    ports:
      - 8080:80

  watchtower:
    environment:
      TZ: ${TZ}
    image: containrrr/watchtower
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    restart: unless-stopped
    networks:
      dockervlan:
        ipv4_address: ${MACVLAN_ADGUARD_IP} # IP address inside the defined range
    ports:
      # DNS
      - 53:53
      # DHCP server
      # - 67:67/udp
      # - 68:68/tcp
      # - 68:68/udp
      # HTTPS/DNS-over-HTTPS
      - 443:443/tcp
      # DNS-over-TLS
      # - 853:853/tcp
      # DNS-over-QUIC
      # - 784:784/udp
      # DNSCrypt
      # - 5443:5443/tcp
      # - 5443:5443/udp
      # WebUI
      - 3000:3000/tcp
    volumes:
      - ${DOCKER_VOLUMES}/adguard/data:/opt/adguardhome/conf
      - ${DOCKER_VOLUMES}/adguard/work:/opt/adguardhome/work

networks:
  dockervlan:
    name: dockervlan
    driver: macvlan
    driver_opts:
      parent: ${NIC} # using ifconfig
    ipam:
      config:
        - subnet: "${MACVLAN_SUBNET}"
          ip_range: "${MACVLAN_ADGUARD_IP}/32"
          gateway: "${MACVLAN_GATEWAY}"

  # tailscale:
  #   privileged: true
  #   network_mode: "host"
  #   container_name: tailscale
  #   image: tailscale/tailscale:latest
  #   logging:
  #     options:
  #       max-size: "10m"
  #       max-file: "3"
  #   volumes:
  #       - "${DOCKER_LARGE_VOLUMES}/tailscale/data:/var/lib"
  #       - "/dev/net/tun:/dev/net/tun"
  #   cap_add:
  #       - NET_ADMIN
  #       - NET_RAW
  #   command: tailscaled
  #   restart: unless-stopped